name: Playwright Tests

on:
  push:
    branches: [ main, master ]    
  pull_request: 
jobs:
  test:
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup Node.js      
      uses: actions/setup-node@v4
      with:
        node-version: lts/*    
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps     

    - name: Start Juice Shop (from source) in background
      run: |
        git clone https://github.com/juice-shop/juice-shop.git juice-shop-src --depth 1
        cd juice-shop-src
        npm ci
        npm start > /tmp/juice_shop.log 2>&1 & echo $! > /tmp/juice_shop_pid

    - name: Wait for app
      run: npx wait-on http://localhost:3000 --timeout 120000

    - name: Run tests (headless)
      run: |
        mkdir -p results
        npx playwright test --reporter=html --reporter="junit=results/junit.xml"

    - name: Upload HTML Playwright Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 14
    - name: Upload JUnit results
      if: always()
      uses: actions/upload-artifact@v4
      with:
          name: junit-results
          path: results/junit.xml

    - name: Stop Juice Shop
      if: always()
      run: |
        [ -f /tmp/juice_shop_pid ] && kill "$(cat /tmp/juice_shop_pid)" || true
